// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0--rc3
// source: vlr/api/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_LIVE        Status = 1
	Status_STATUS_UPCOMING    Status = 2
	Status_STATUS_COMPLETED   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_LIVE",
		2: "STATUS_UPCOMING",
		3: "STATUS_COMPLETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_LIVE":        1,
		"STATUS_UPCOMING":    2,
		"STATUS_COMPLETED":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_vlr_api_api_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_vlr_api_api_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_vlr_api_api_proto_rawDescGZIP(), []int{0}
}

type Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head   *Match_Head   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Versus *Match_Versus `protobuf:"bytes,2,opt,name=versus,proto3" json:"versus,omitempty"`
	Maps   []*Match_Map  `protobuf:"bytes,3,rep,name=maps,proto3" json:"maps,omitempty"`
}

func (x *Match) Reset() {
	*x = Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vlr_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_vlr_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_vlr_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetHead() *Match_Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Match) GetVersus() *Match_Versus {
	if x != nil {
		return x.Versus
	}
	return nil
}

func (x *Match) GetMaps() []*Match_Map {
	if x != nil {
		return x.Maps
	}
	return nil
}

type Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// vlr.gg/team/{team_id}
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Team) Reset() {
	*x = Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vlr_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_vlr_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_vlr_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Match_Head struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// vlr.gg/{match_id}
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	// vlr.gg/event/{event_id}
	EventId  string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
}

func (x *Match_Head) Reset() {
	*x = Match_Head{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vlr_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match_Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match_Head) ProtoMessage() {}

func (x *Match_Head) ProtoReflect() protoreflect.Message {
	mi := &file_vlr_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match_Head.ProtoReflect.Descriptor instead.
func (*Match_Head) Descriptor() ([]byte, []int) {
	return file_vlr_api_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Match_Head) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *Match_Head) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Match_Head) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

type Match_Versus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team1 *Team `protobuf:"bytes,1,opt,name=team1,proto3" json:"team1,omitempty"`
	// the map score of the first team
	Score1 int32 `protobuf:"varint,2,opt,name=score1,proto3" json:"score1,omitempty"`
	Team2  *Team `protobuf:"bytes,3,opt,name=team2,proto3" json:"team2,omitempty"`
	// the map score of the second team
	Score2 int32 `protobuf:"varint,4,opt,name=score2,proto3" json:"score2,omitempty"`
}

func (x *Match_Versus) Reset() {
	*x = Match_Versus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vlr_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match_Versus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match_Versus) ProtoMessage() {}

func (x *Match_Versus) ProtoReflect() protoreflect.Message {
	mi := &file_vlr_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match_Versus.ProtoReflect.Descriptor instead.
func (*Match_Versus) Descriptor() ([]byte, []int) {
	return file_vlr_api_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Match_Versus) GetTeam1() *Team {
	if x != nil {
		return x.Team1
	}
	return nil
}

func (x *Match_Versus) GetScore1() int32 {
	if x != nil {
		return x.Score1
	}
	return 0
}

func (x *Match_Versus) GetTeam2() *Team {
	if x != nil {
		return x.Team2
	}
	return nil
}

func (x *Match_Versus) GetScore2() int32 {
	if x != nil {
		return x.Score2
	}
	return 0
}

type Match_Map struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rounds []*Match_Map_Round `protobuf:"bytes,3,rep,name=rounds,proto3" json:"rounds,omitempty"`
}

func (x *Match_Map) Reset() {
	*x = Match_Map{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vlr_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match_Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match_Map) ProtoMessage() {}

func (x *Match_Map) ProtoReflect() protoreflect.Message {
	mi := &file_vlr_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match_Map.ProtoReflect.Descriptor instead.
func (*Match_Map) Descriptor() ([]byte, []int) {
	return file_vlr_api_api_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Match_Map) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Match_Map) GetRounds() []*Match_Map_Round {
	if x != nil {
		return x.Rounds
	}
	return nil
}

type Match_Map_Round struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the score of the first team
	Score1 int32 `protobuf:"varint,2,opt,name=score1,proto3" json:"score1,omitempty"`
	// the score of the second team
	Score2 int32 `protobuf:"varint,3,opt,name=score2,proto3" json:"score2,omitempty"`
}

func (x *Match_Map_Round) Reset() {
	*x = Match_Map_Round{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vlr_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match_Map_Round) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match_Map_Round) ProtoMessage() {}

func (x *Match_Map_Round) ProtoReflect() protoreflect.Message {
	mi := &file_vlr_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match_Map_Round.ProtoReflect.Descriptor instead.
func (*Match_Map_Round) Descriptor() ([]byte, []int) {
	return file_vlr_api_api_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Match_Map_Round) GetScore1() int32 {
	if x != nil {
		return x.Score1
	}
	return 0
}

func (x *Match_Map_Round) GetScore2() int32 {
	if x != nil {
		return x.Score2
	}
	return 0
}

var File_vlr_api_api_proto protoreflect.FileDescriptor

var file_vlr_api_api_proto_rawDesc = []byte{
	0x0a, 0x11, 0x76, 0x6c, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x76, 0x6c, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x04,
	0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x27, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x6c, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x12, 0x2d, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x73, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x76, 0x6c, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x2e, 0x56, 0x65, 0x72, 0x73, 0x75, 0x73, 0x52, 0x06, 0x76, 0x65, 0x72, 0x73, 0x75, 0x73, 0x12,
	0x26, 0x0a, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x76, 0x6c, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x4d, 0x61,
	0x70, 0x52, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x1a, 0x75, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x82,
	0x01, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x73, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x65, 0x61,
	0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x6c, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x31, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x31, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x32, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x6c, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x32, 0x1a, 0x84, 0x01, 0x0a, 0x03, 0x4d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x30, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x76, 0x6c, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x2e,
	0x4d, 0x61, 0x70, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x73, 0x1a, 0x37, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x22, 0x33, 0x0a, 0x04, 0x54, 0x65,
	0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x2a,
	0x5c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4c, 0x49, 0x56, 0x45,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x50, 0x43,
	0x4f, 0x4d, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x42, 0x23, 0x5a,
	0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x72, 0x61,
	0x72, 0x6b, 0x65, 0x6e, 0x2f, 0x76, 0x6c, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vlr_api_api_proto_rawDescOnce sync.Once
	file_vlr_api_api_proto_rawDescData = file_vlr_api_api_proto_rawDesc
)

func file_vlr_api_api_proto_rawDescGZIP() []byte {
	file_vlr_api_api_proto_rawDescOnce.Do(func() {
		file_vlr_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_vlr_api_api_proto_rawDescData)
	})
	return file_vlr_api_api_proto_rawDescData
}

var file_vlr_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vlr_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vlr_api_api_proto_goTypes = []interface{}{
	(Status)(0),                   // 0: vlr.api.Status
	(*Match)(nil),                 // 1: vlr.api.Match
	(*Team)(nil),                  // 2: vlr.api.Team
	(*Match_Head)(nil),            // 3: vlr.api.Match.Head
	(*Match_Versus)(nil),          // 4: vlr.api.Match.Versus
	(*Match_Map)(nil),             // 5: vlr.api.Match.Map
	(*Match_Map_Round)(nil),       // 6: vlr.api.Match.Map.Round
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_vlr_api_api_proto_depIdxs = []int32{
	3, // 0: vlr.api.Match.head:type_name -> vlr.api.Match.Head
	4, // 1: vlr.api.Match.versus:type_name -> vlr.api.Match.Versus
	5, // 2: vlr.api.Match.maps:type_name -> vlr.api.Match.Map
	7, // 3: vlr.api.Match.Head.date_time:type_name -> google.protobuf.Timestamp
	2, // 4: vlr.api.Match.Versus.team1:type_name -> vlr.api.Team
	2, // 5: vlr.api.Match.Versus.team2:type_name -> vlr.api.Team
	6, // 6: vlr.api.Match.Map.rounds:type_name -> vlr.api.Match.Map.Round
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_vlr_api_api_proto_init() }
func file_vlr_api_api_proto_init() {
	if File_vlr_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vlr_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vlr_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vlr_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match_Head); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vlr_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match_Versus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vlr_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match_Map); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vlr_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match_Map_Round); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vlr_api_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vlr_api_api_proto_goTypes,
		DependencyIndexes: file_vlr_api_api_proto_depIdxs,
		EnumInfos:         file_vlr_api_api_proto_enumTypes,
		MessageInfos:      file_vlr_api_api_proto_msgTypes,
	}.Build()
	File_vlr_api_api_proto = out.File
	file_vlr_api_api_proto_rawDesc = nil
	file_vlr_api_api_proto_goTypes = nil
	file_vlr_api_api_proto_depIdxs = nil
}
